apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: raj-pod-cluster-access
subjects:
  - kind: user
    name: raj
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-cluster-role
  apiGroup: rbac.authorization.k8s.io